#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_Ekstraklasa
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ekstraklasa")]
	public partial class DataEkstraklasaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBRAMKI(BRAMKI instance);
    partial void UpdateBRAMKI(BRAMKI instance);
    partial void DeleteBRAMKI(BRAMKI instance);
    partial void InsertDRUZYNY(DRUZYNY instance);
    partial void UpdateDRUZYNY(DRUZYNY instance);
    partial void DeleteDRUZYNY(DRUZYNY instance);
    partial void InsertPILKARZE(PILKARZE instance);
    partial void UpdatePILKARZE(PILKARZE instance);
    partial void DeletePILKARZE(PILKARZE instance);
    partial void InsertKARTKI(KARTKI instance);
    partial void UpdateKARTKI(KARTKI instance);
    partial void DeleteKARTKI(KARTKI instance);
    partial void InsertSPOTKANIA(SPOTKANIA instance);
    partial void UpdateSPOTKANIA(SPOTKANIA instance);
    partial void DeleteSPOTKANIA(SPOTKANIA instance);
    partial void InsertTRENERZY(TRENERZY instance);
    partial void UpdateTRENERZY(TRENERZY instance);
    partial void DeleteTRENERZY(TRENERZY instance);
    partial void InsertSEDZIOWIE(SEDZIOWIE instance);
    partial void UpdateSEDZIOWIE(SEDZIOWIE instance);
    partial void DeleteSEDZIOWIE(SEDZIOWIE instance);
    #endregion
		
		public DataEkstraklasaDataContext() : 
				base(global::Projekt_Ekstraklasa.Properties.Settings.Default.C__USERS_DARIU_APPDATA_LOCAL_MICROSOFT_VISUALSTUDIO_SSDT_EKSTRAKLASA_MDFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEkstraklasaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEkstraklasaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEkstraklasaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEkstraklasaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BRAMKI> BRAMKIs
		{
			get
			{
				return this.GetTable<BRAMKI>();
			}
		}
		
		public System.Data.Linq.Table<DRUZYNY> DRUZYNies
		{
			get
			{
				return this.GetTable<DRUZYNY>();
			}
		}
		
		public System.Data.Linq.Table<PILKARZE> PILKARZEs
		{
			get
			{
				return this.GetTable<PILKARZE>();
			}
		}
		
		public System.Data.Linq.Table<KARTKI> KARTKIs
		{
			get
			{
				return this.GetTable<KARTKI>();
			}
		}
		
		public System.Data.Linq.Table<SPOTKANIA> SPOTKANIAs
		{
			get
			{
				return this.GetTable<SPOTKANIA>();
			}
		}
		
		public System.Data.Linq.Table<TRENERZY> TRENERZies
		{
			get
			{
				return this.GetTable<TRENERZY>();
			}
		}
		
		public System.Data.Linq.Table<SEDZIOWIE> SEDZIOWIEs
		{
			get
			{
				return this.GetTable<SEDZIOWIE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BRAMKI")]
	public partial class BRAMKI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_bramka;
		
		private decimal _Id_spot;
		
		private decimal _Id_strzelec;
		
		private decimal _Id_bramkarz;
		
		private System.Nullable<int> _Czas_bramki;
		
		private EntityRef<PILKARZE> _PILKARZE;
		
		private EntityRef<PILKARZE> _PILKARZE1;
		
		private EntityRef<SPOTKANIA> _SPOTKANIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnId_SpotkaniaChanging(decimal value);
    partial void OnId_SpotkaniaChanged();
    partial void OnId_StrzelcaChanging(decimal value);
    partial void OnId_StrzelcaChanged();
    partial void OnId_BramkarzaChanging(decimal value);
    partial void OnId_BramkarzaChanged();
    partial void OnCzas_BramkiChanging(System.Nullable<int> value);
    partial void OnCzas_BramkiChanged();
    #endregion
		
		public BRAMKI()
		{
			this._PILKARZE = default(EntityRef<PILKARZE>);
			this._PILKARZE1 = default(EntityRef<PILKARZE>);
			this._SPOTKANIA = default(EntityRef<SPOTKANIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_bramka", Storage="_Id_bramka", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_bramka;
			}
			set
			{
				if ((this._Id_bramka != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_bramka = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_spot", Storage="_Id_spot", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_Spotkania
		{
			get
			{
				return this._Id_spot;
			}
			set
			{
				if ((this._Id_spot != value))
				{
					this.OnId_SpotkaniaChanging(value);
					this.SendPropertyChanging();
					this._Id_spot = value;
					this.SendPropertyChanged("Id_Spotkania");
					this.OnId_SpotkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_strzelec", Storage="_Id_strzelec", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_Strzelca
		{
			get
			{
				return this._Id_strzelec;
			}
			set
			{
				if ((this._Id_strzelec != value))
				{
					this.OnId_StrzelcaChanging(value);
					this.SendPropertyChanging();
					this._Id_strzelec = value;
					this.SendPropertyChanged("Id_Strzelca");
					this.OnId_StrzelcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_bramkarz", Storage="_Id_bramkarz", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_Bramkarza
		{
			get
			{
				return this._Id_bramkarz;
			}
			set
			{
				if ((this._Id_bramkarz != value))
				{
					this.OnId_BramkarzaChanging(value);
					this.SendPropertyChanging();
					this._Id_bramkarz = value;
					this.SendPropertyChanged("Id_Bramkarza");
					this.OnId_BramkarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Czas_bramki", Storage="_Czas_bramki", DbType="Int")]
		public System.Nullable<int> Czas_Bramki
		{
			get
			{
				return this._Czas_bramki;
			}
			set
			{
				if ((this._Czas_bramki != value))
				{
					this.OnCzas_BramkiChanging(value);
					this.SendPropertyChanging();
					this._Czas_bramki = value;
					this.SendPropertyChanged("Czas_Bramki");
					this.OnCzas_BramkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_BRAMKI", Storage="_PILKARZE", ThisKey="Id_Bramkarza", OtherKey="Id", IsForeignKey=true)]
		public PILKARZE PILKARZE
		{
			get
			{
				return this._PILKARZE.Entity;
			}
			set
			{
				PILKARZE previousValue = this._PILKARZE.Entity;
				if (((previousValue != value) 
							|| (this._PILKARZE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILKARZE.Entity = null;
						previousValue.BRAMKIs.Remove(this);
					}
					this._PILKARZE.Entity = value;
					if ((value != null))
					{
						value.BRAMKIs.Add(this);
						this._Id_bramkarz = value.Id;
					}
					else
					{
						this._Id_bramkarz = default(decimal);
					}
					this.SendPropertyChanged("PILKARZE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_BRAMKI1", Storage="_PILKARZE1", ThisKey="Id_Strzelca", OtherKey="Id", IsForeignKey=true)]
		public PILKARZE PILKARZE1
		{
			get
			{
				return this._PILKARZE1.Entity;
			}
			set
			{
				PILKARZE previousValue = this._PILKARZE1.Entity;
				if (((previousValue != value) 
							|| (this._PILKARZE1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILKARZE1.Entity = null;
						previousValue.BRAMKIs1.Remove(this);
					}
					this._PILKARZE1.Entity = value;
					if ((value != null))
					{
						value.BRAMKIs1.Add(this);
						this._Id_strzelec = value.Id;
					}
					else
					{
						this._Id_strzelec = default(decimal);
					}
					this.SendPropertyChanged("PILKARZE1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_BRAMKI", Storage="_SPOTKANIA", ThisKey="Id_Spotkania", OtherKey="Id", IsForeignKey=true)]
		public SPOTKANIA SPOTKANIA
		{
			get
			{
				return this._SPOTKANIA.Entity;
			}
			set
			{
				SPOTKANIA previousValue = this._SPOTKANIA.Entity;
				if (((previousValue != value) 
							|| (this._SPOTKANIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SPOTKANIA.Entity = null;
						previousValue.BRAMKIs.Remove(this);
					}
					this._SPOTKANIA.Entity = value;
					if ((value != null))
					{
						value.BRAMKIs.Add(this);
						this._Id_spot = value.Id;
					}
					else
					{
						this._Id_spot = default(decimal);
					}
					this.SendPropertyChanged("SPOTKANIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DRUZYNY")]
	public partial class DRUZYNY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_druz;
		
		private string _Nazwa_druz;
		
		private string _Wlasciciel_druz;
		
		private string _Siedziba_druz;
		
		private System.Nullable<int> _Ilosc_strzelonych_goli_druz;
		
		private System.Nullable<int> _Ilosc_rozegranych_meczy_druz;
		
		private System.Nullable<int> _Ilosc_punktow_druz;
		
		private EntitySet<PILKARZE> _PILKARZEs;
		
		private EntitySet<SPOTKANIA> _SPOTKANIAs;
		
		private EntitySet<SPOTKANIA> _SPOTKANIAs1;
		
		private EntitySet<TRENERZY> _TRENERZies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnWłaścicielChanging(string value);
    partial void OnWłaścicielChanged();
    partial void OnSiedzibaChanging(string value);
    partial void OnSiedzibaChanged();
    partial void OnStrzelone_GoleChanging(System.Nullable<int> value);
    partial void OnStrzelone_GoleChanged();
    partial void OnRozegrane_MeczeChanging(System.Nullable<int> value);
    partial void OnRozegrane_MeczeChanged();
    partial void OnPunktyChanging(System.Nullable<int> value);
    partial void OnPunktyChanged();
    #endregion
		
		public DRUZYNY()
		{
			this._PILKARZEs = new EntitySet<PILKARZE>(new Action<PILKARZE>(this.attach_PILKARZEs), new Action<PILKARZE>(this.detach_PILKARZEs));
			this._SPOTKANIAs = new EntitySet<SPOTKANIA>(new Action<SPOTKANIA>(this.attach_SPOTKANIAs), new Action<SPOTKANIA>(this.detach_SPOTKANIAs));
			this._SPOTKANIAs1 = new EntitySet<SPOTKANIA>(new Action<SPOTKANIA>(this.attach_SPOTKANIAs1), new Action<SPOTKANIA>(this.detach_SPOTKANIAs1));
			this._TRENERZies = new EntitySet<TRENERZY>(new Action<TRENERZY>(this.attach_TRENERZies), new Action<TRENERZY>(this.detach_TRENERZies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_druz", Storage="_Id_druz", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_druz;
			}
			set
			{
				if ((this._Id_druz != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_druz = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Nazwa_druz", Storage="_Nazwa_druz", DbType="VarChar(15)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa_druz;
			}
			set
			{
				if ((this._Nazwa_druz != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa_druz = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Wlasciciel_druz", Storage="_Wlasciciel_druz", DbType="VarChar(15)")]
		public string Właściciel
		{
			get
			{
				return this._Wlasciciel_druz;
			}
			set
			{
				if ((this._Wlasciciel_druz != value))
				{
					this.OnWłaścicielChanging(value);
					this.SendPropertyChanging();
					this._Wlasciciel_druz = value;
					this.SendPropertyChanged("Właściciel");
					this.OnWłaścicielChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Siedziba_druz", Storage="_Siedziba_druz", DbType="VarChar(15)")]
		public string Siedziba
		{
			get
			{
				return this._Siedziba_druz;
			}
			set
			{
				if ((this._Siedziba_druz != value))
				{
					this.OnSiedzibaChanging(value);
					this.SendPropertyChanging();
					this._Siedziba_druz = value;
					this.SendPropertyChanged("Siedziba");
					this.OnSiedzibaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_strzelonych_goli_druz", Storage="_Ilosc_strzelonych_goli_druz", DbType="Int")]
		public System.Nullable<int> Strzelone_Gole
		{
			get
			{
				return this._Ilosc_strzelonych_goli_druz;
			}
			set
			{
				if ((this._Ilosc_strzelonych_goli_druz != value))
				{
					this.OnStrzelone_GoleChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_strzelonych_goli_druz = value;
					this.SendPropertyChanged("Strzelone_Gole");
					this.OnStrzelone_GoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_rozegranych_meczy_druz", Storage="_Ilosc_rozegranych_meczy_druz", DbType="Int")]
		public System.Nullable<int> Rozegrane_Mecze
		{
			get
			{
				return this._Ilosc_rozegranych_meczy_druz;
			}
			set
			{
				if ((this._Ilosc_rozegranych_meczy_druz != value))
				{
					this.OnRozegrane_MeczeChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_rozegranych_meczy_druz = value;
					this.SendPropertyChanged("Rozegrane_Mecze");
					this.OnRozegrane_MeczeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_punktow_druz", Storage="_Ilosc_punktow_druz", DbType="Int")]
		public System.Nullable<int> Punkty
		{
			get
			{
				return this._Ilosc_punktow_druz;
			}
			set
			{
				if ((this._Ilosc_punktow_druz != value))
				{
					this.OnPunktyChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_punktow_druz = value;
					this.SendPropertyChanged("Punkty");
					this.OnPunktyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_PILKARZE", Storage="_PILKARZEs", ThisKey="Id", OtherKey="Id_Drużyny")]
		public EntitySet<PILKARZE> PILKARZEs
		{
			get
			{
				return this._PILKARZEs;
			}
			set
			{
				this._PILKARZEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_SPOTKANIA", Storage="_SPOTKANIAs", ThisKey="Id", OtherKey="Id_Gościa")]
		public EntitySet<SPOTKANIA> SPOTKANIAs
		{
			get
			{
				return this._SPOTKANIAs;
			}
			set
			{
				this._SPOTKANIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_SPOTKANIA1", Storage="_SPOTKANIAs1", ThisKey="Id", OtherKey="Id_Gospodarza")]
		public EntitySet<SPOTKANIA> SPOTKANIAs1
		{
			get
			{
				return this._SPOTKANIAs1;
			}
			set
			{
				this._SPOTKANIAs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_TRENERZY", Storage="_TRENERZies", ThisKey="Id", OtherKey="Druzyna")]
		public EntitySet<TRENERZY> TRENERZies
		{
			get
			{
				return this._TRENERZies;
			}
			set
			{
				this._TRENERZies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PILKARZEs(PILKARZE entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = this;
		}
		
		private void detach_PILKARZEs(PILKARZE entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = null;
		}
		
		private void attach_SPOTKANIAs(SPOTKANIA entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = this;
		}
		
		private void detach_SPOTKANIAs(SPOTKANIA entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = null;
		}
		
		private void attach_SPOTKANIAs1(SPOTKANIA entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY1 = this;
		}
		
		private void detach_SPOTKANIAs1(SPOTKANIA entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY1 = null;
		}
		
		private void attach_TRENERZies(TRENERZY entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = this;
		}
		
		private void detach_TRENERZies(TRENERZY entity)
		{
			this.SendPropertyChanging();
			entity.DRUZYNY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PILKARZE")]
	public partial class PILKARZE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_pilk;
		
		private System.Nullable<decimal> _Id_druz;
		
		private string _Imie_pilk;
		
		private string _Nazwisko_pilk;
		
		private System.Nullable<System.DateTime> _Data_ur_pilk;
		
		private System.Nullable<int> _Ilosc_meczy_pilk;
		
		private System.Nullable<int> _Ilosc_strzelonych_goli_pilk;
		
		private System.Nullable<int> _Ilosc_wpuszczonych_goli_pilk;
		
		private System.Nullable<int> _Ilosc_zoltych_kartek_pilk;
		
		private System.Nullable<int> _Ilosc_czerwonych_kartek_pilk;
		
		private string _Specjalizacja_pilk;
		
		private EntitySet<BRAMKI> _BRAMKIs;
		
		private EntitySet<BRAMKI> _BRAMKIs1;
		
		private EntitySet<KARTKI> _KARTKIs;
		
		private EntityRef<DRUZYNY> _DRUZYNY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnId_DrużynyChanging(System.Nullable<decimal> value);
    partial void OnId_DrużynyChanged();
    partial void OnImięChanging(string value);
    partial void OnImięChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnData_UrodzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnData_UrodzeniaChanged();
    partial void OnIlość_MeczyChanging(System.Nullable<int> value);
    partial void OnIlość_MeczyChanged();
    partial void OnStrzelone_GoleChanging(System.Nullable<int> value);
    partial void OnStrzelone_GoleChanged();
    partial void OnWpuszczone_PiłkiChanging(System.Nullable<int> value);
    partial void OnWpuszczone_PiłkiChanged();
    partial void OnŻółte_KartkiChanging(System.Nullable<int> value);
    partial void OnŻółte_KartkiChanged();
    partial void OnCzerwone_KartkiChanging(System.Nullable<int> value);
    partial void OnCzerwone_KartkiChanged();
    partial void OnPozycjaChanging(string value);
    partial void OnPozycjaChanged();
    #endregion
		
		public PILKARZE()
		{
			this._BRAMKIs = new EntitySet<BRAMKI>(new Action<BRAMKI>(this.attach_BRAMKIs), new Action<BRAMKI>(this.detach_BRAMKIs));
			this._BRAMKIs1 = new EntitySet<BRAMKI>(new Action<BRAMKI>(this.attach_BRAMKIs1), new Action<BRAMKI>(this.detach_BRAMKIs1));
			this._KARTKIs = new EntitySet<KARTKI>(new Action<KARTKI>(this.attach_KARTKIs), new Action<KARTKI>(this.detach_KARTKIs));
			this._DRUZYNY = default(EntityRef<DRUZYNY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_pilk", Storage="_Id_pilk", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_pilk;
			}
			set
			{
				if ((this._Id_pilk != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_pilk = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_druz", Storage="_Id_druz", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Id_Drużyny
		{
			get
			{
				return this._Id_druz;
			}
			set
			{
				if ((this._Id_druz != value))
				{
					this.OnId_DrużynyChanging(value);
					this.SendPropertyChanging();
					this._Id_druz = value;
					this.SendPropertyChanged("Id_Drużyny");
					this.OnId_DrużynyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Imie_pilk", Storage="_Imie_pilk", DbType="VarChar(15)")]
		public string Imię
		{
			get
			{
				return this._Imie_pilk;
			}
			set
			{
				if ((this._Imie_pilk != value))
				{
					this.OnImięChanging(value);
					this.SendPropertyChanging();
					this._Imie_pilk = value;
					this.SendPropertyChanged("Imię");
					this.OnImięChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Nazwisko_pilk", Storage="_Nazwisko_pilk", DbType="VarChar(15)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko_pilk;
			}
			set
			{
				if ((this._Nazwisko_pilk != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko_pilk = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Data_ur_pilk", Storage="_Data_ur_pilk", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Urodzenia
		{
			get
			{
				return this._Data_ur_pilk;
			}
			set
			{
				if ((this._Data_ur_pilk != value))
				{
					this.OnData_UrodzeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_ur_pilk = value;
					this.SendPropertyChanged("Data_Urodzenia");
					this.OnData_UrodzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_meczy_pilk", Storage="_Ilosc_meczy_pilk", DbType="Int")]
		public System.Nullable<int> Ilość_Meczy
		{
			get
			{
				return this._Ilosc_meczy_pilk;
			}
			set
			{
				if ((this._Ilosc_meczy_pilk != value))
				{
					this.OnIlość_MeczyChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_meczy_pilk = value;
					this.SendPropertyChanged("Ilość_Meczy");
					this.OnIlość_MeczyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_strzelonych_goli_pilk", Storage="_Ilosc_strzelonych_goli_pilk", DbType="Int")]
		public System.Nullable<int> Strzelone_Gole
		{
			get
			{
				return this._Ilosc_strzelonych_goli_pilk;
			}
			set
			{
				if ((this._Ilosc_strzelonych_goli_pilk != value))
				{
					this.OnStrzelone_GoleChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_strzelonych_goli_pilk = value;
					this.SendPropertyChanged("Strzelone_Gole");
					this.OnStrzelone_GoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_wpuszczonych_goli_pilk", Storage="_Ilosc_wpuszczonych_goli_pilk", DbType="Int")]
		public System.Nullable<int> Wpuszczone_Piłki
		{
			get
			{
				return this._Ilosc_wpuszczonych_goli_pilk;
			}
			set
			{
				if ((this._Ilosc_wpuszczonych_goli_pilk != value))
				{
					this.OnWpuszczone_PiłkiChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_wpuszczonych_goli_pilk = value;
					this.SendPropertyChanged("Wpuszczone_Piłki");
					this.OnWpuszczone_PiłkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_zoltych_kartek_pilk", Storage="_Ilosc_zoltych_kartek_pilk", DbType="Int")]
		public System.Nullable<int> Żółte_Kartki
		{
			get
			{
				return this._Ilosc_zoltych_kartek_pilk;
			}
			set
			{
				if ((this._Ilosc_zoltych_kartek_pilk != value))
				{
					this.OnŻółte_KartkiChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_zoltych_kartek_pilk = value;
					this.SendPropertyChanged("Żółte_Kartki");
					this.OnŻółte_KartkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_czerwonych_kartek_pilk", Storage="_Ilosc_czerwonych_kartek_pilk", DbType="Int")]
		public System.Nullable<int> Czerwone_Kartki
		{
			get
			{
				return this._Ilosc_czerwonych_kartek_pilk;
			}
			set
			{
				if ((this._Ilosc_czerwonych_kartek_pilk != value))
				{
					this.OnCzerwone_KartkiChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_czerwonych_kartek_pilk = value;
					this.SendPropertyChanged("Czerwone_Kartki");
					this.OnCzerwone_KartkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Specjalizacja_pilk", Storage="_Specjalizacja_pilk", DbType="VarChar(15)")]
		public string Pozycja
		{
			get
			{
				return this._Specjalizacja_pilk;
			}
			set
			{
				if ((this._Specjalizacja_pilk != value))
				{
					this.OnPozycjaChanging(value);
					this.SendPropertyChanging();
					this._Specjalizacja_pilk = value;
					this.SendPropertyChanged("Pozycja");
					this.OnPozycjaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_BRAMKI", Storage="_BRAMKIs", ThisKey="Id", OtherKey="Id_Bramkarza")]
		public EntitySet<BRAMKI> BRAMKIs
		{
			get
			{
				return this._BRAMKIs;
			}
			set
			{
				this._BRAMKIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_BRAMKI1", Storage="_BRAMKIs1", ThisKey="Id", OtherKey="Id_Strzelca")]
		public EntitySet<BRAMKI> BRAMKIs1
		{
			get
			{
				return this._BRAMKIs1;
			}
			set
			{
				this._BRAMKIs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_KARTKI", Storage="_KARTKIs", ThisKey="Id", OtherKey="Id_pilk")]
		public EntitySet<KARTKI> KARTKIs
		{
			get
			{
				return this._KARTKIs;
			}
			set
			{
				this._KARTKIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_PILKARZE", Storage="_DRUZYNY", ThisKey="Id_Drużyny", OtherKey="Id", IsForeignKey=true)]
		public DRUZYNY DRUZYNY
		{
			get
			{
				return this._DRUZYNY.Entity;
			}
			set
			{
				DRUZYNY previousValue = this._DRUZYNY.Entity;
				if (((previousValue != value) 
							|| (this._DRUZYNY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DRUZYNY.Entity = null;
						previousValue.PILKARZEs.Remove(this);
					}
					this._DRUZYNY.Entity = value;
					if ((value != null))
					{
						value.PILKARZEs.Add(this);
						this._Id_druz = value.Id;
					}
					else
					{
						this._Id_druz = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("DRUZYNY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BRAMKIs(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE = this;
		}
		
		private void detach_BRAMKIs(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE = null;
		}
		
		private void attach_BRAMKIs1(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE1 = this;
		}
		
		private void detach_BRAMKIs1(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE1 = null;
		}
		
		private void attach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE = this;
		}
		
		private void detach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.PILKARZE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KARTKI")]
	public partial class KARTKI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_kart;
		
		private decimal _Id_pilk;
		
		private decimal _Id_sed;
		
		private System.Nullable<decimal> _Id_spot;
		
		private System.Nullable<int> _Rodzaj_kartki;
		
		private EntityRef<PILKARZE> _PILKARZE;
		
		private EntityRef<SPOTKANIA> _SPOTKANIA;
		
		private EntityRef<SEDZIOWIE> _SEDZIOWIE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_kartChanging(decimal value);
    partial void OnId_kartChanged();
    partial void OnId_pilkChanging(decimal value);
    partial void OnId_pilkChanged();
    partial void OnId_sedChanging(decimal value);
    partial void OnId_sedChanged();
    partial void OnId_spotChanging(System.Nullable<decimal> value);
    partial void OnId_spotChanged();
    partial void OnRodzaj_kartkiChanging(System.Nullable<int> value);
    partial void OnRodzaj_kartkiChanged();
    #endregion
		
		public KARTKI()
		{
			this._PILKARZE = default(EntityRef<PILKARZE>);
			this._SPOTKANIA = default(EntityRef<SPOTKANIA>);
			this._SEDZIOWIE = default(EntityRef<SEDZIOWIE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_kart", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id_kart
		{
			get
			{
				return this._Id_kart;
			}
			set
			{
				if ((this._Id_kart != value))
				{
					this.OnId_kartChanging(value);
					this.SendPropertyChanging();
					this._Id_kart = value;
					this.SendPropertyChanged("Id_kart");
					this.OnId_kartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_pilk", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_pilk
		{
			get
			{
				return this._Id_pilk;
			}
			set
			{
				if ((this._Id_pilk != value))
				{
					if (this._PILKARZE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_pilkChanging(value);
					this.SendPropertyChanging();
					this._Id_pilk = value;
					this.SendPropertyChanged("Id_pilk");
					this.OnId_pilkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sed", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_sed
		{
			get
			{
				return this._Id_sed;
			}
			set
			{
				if ((this._Id_sed != value))
				{
					if (this._SEDZIOWIE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_sedChanging(value);
					this.SendPropertyChanging();
					this._Id_sed = value;
					this.SendPropertyChanged("Id_sed");
					this.OnId_sedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_spot", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Id_spot
		{
			get
			{
				return this._Id_spot;
			}
			set
			{
				if ((this._Id_spot != value))
				{
					if (this._SPOTKANIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_spotChanging(value);
					this.SendPropertyChanging();
					this._Id_spot = value;
					this.SendPropertyChanged("Id_spot");
					this.OnId_spotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rodzaj_kartki", DbType="Int")]
		public System.Nullable<int> Rodzaj_kartki
		{
			get
			{
				return this._Rodzaj_kartki;
			}
			set
			{
				if ((this._Rodzaj_kartki != value))
				{
					this.OnRodzaj_kartkiChanging(value);
					this.SendPropertyChanging();
					this._Rodzaj_kartki = value;
					this.SendPropertyChanged("Rodzaj_kartki");
					this.OnRodzaj_kartkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILKARZE_KARTKI", Storage="_PILKARZE", ThisKey="Id_pilk", OtherKey="Id", IsForeignKey=true)]
		public PILKARZE PILKARZE
		{
			get
			{
				return this._PILKARZE.Entity;
			}
			set
			{
				PILKARZE previousValue = this._PILKARZE.Entity;
				if (((previousValue != value) 
							|| (this._PILKARZE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILKARZE.Entity = null;
						previousValue.KARTKIs.Remove(this);
					}
					this._PILKARZE.Entity = value;
					if ((value != null))
					{
						value.KARTKIs.Add(this);
						this._Id_pilk = value.Id;
					}
					else
					{
						this._Id_pilk = default(decimal);
					}
					this.SendPropertyChanged("PILKARZE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_KARTKI", Storage="_SPOTKANIA", ThisKey="Id_spot", OtherKey="Id", IsForeignKey=true)]
		public SPOTKANIA SPOTKANIA
		{
			get
			{
				return this._SPOTKANIA.Entity;
			}
			set
			{
				SPOTKANIA previousValue = this._SPOTKANIA.Entity;
				if (((previousValue != value) 
							|| (this._SPOTKANIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SPOTKANIA.Entity = null;
						previousValue.KARTKIs.Remove(this);
					}
					this._SPOTKANIA.Entity = value;
					if ((value != null))
					{
						value.KARTKIs.Add(this);
						this._Id_spot = value.Id;
					}
					else
					{
						this._Id_spot = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("SPOTKANIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEDZIOWIE_KARTKI", Storage="_SEDZIOWIE", ThisKey="Id_sed", OtherKey="Id", IsForeignKey=true)]
		public SEDZIOWIE SEDZIOWIE
		{
			get
			{
				return this._SEDZIOWIE.Entity;
			}
			set
			{
				SEDZIOWIE previousValue = this._SEDZIOWIE.Entity;
				if (((previousValue != value) 
							|| (this._SEDZIOWIE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SEDZIOWIE.Entity = null;
						previousValue.KARTKIs.Remove(this);
					}
					this._SEDZIOWIE.Entity = value;
					if ((value != null))
					{
						value.KARTKIs.Add(this);
						this._Id_sed = value.Id;
					}
					else
					{
						this._Id_sed = default(decimal);
					}
					this.SendPropertyChanged("SEDZIOWIE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SPOTKANIA")]
	public partial class SPOTKANIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_spot;
		
		private decimal _Id_gospo;
		
		private decimal _Id_gosc;
		
		private System.Nullable<System.DateTime> _Data_spot;
		
		private string _Miejsce_spot;
		
		private System.Nullable<int> _Wynik_gospo;
		
		private System.Nullable<int> _Wynik_gosc;
		
		private EntitySet<BRAMKI> _BRAMKIs;
		
		private EntitySet<KARTKI> _KARTKIs;
		
		private EntitySet<SEDZIOWIE> _SEDZIOWIEs;
		
		private EntityRef<DRUZYNY> _DRUZYNY;
		
		private EntityRef<DRUZYNY> _DRUZYNY1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnId_GospodarzaChanging(decimal value);
    partial void OnId_GospodarzaChanged();
    partial void OnId_GościaChanging(decimal value);
    partial void OnId_GościaChanged();
    partial void OnData_SpotkaniaChanging(System.Nullable<System.DateTime> value);
    partial void OnData_SpotkaniaChanged();
    partial void OnMiejsce_SpotkaniaChanging(string value);
    partial void OnMiejsce_SpotkaniaChanged();
    partial void OnWynik_GospodarzaChanging(System.Nullable<int> value);
    partial void OnWynik_GospodarzaChanged();
    partial void OnWynik_GościaChanging(System.Nullable<int> value);
    partial void OnWynik_GościaChanged();
    #endregion
		
		public SPOTKANIA()
		{
			this._BRAMKIs = new EntitySet<BRAMKI>(new Action<BRAMKI>(this.attach_BRAMKIs), new Action<BRAMKI>(this.detach_BRAMKIs));
			this._KARTKIs = new EntitySet<KARTKI>(new Action<KARTKI>(this.attach_KARTKIs), new Action<KARTKI>(this.detach_KARTKIs));
			this._SEDZIOWIEs = new EntitySet<SEDZIOWIE>(new Action<SEDZIOWIE>(this.attach_SEDZIOWIEs), new Action<SEDZIOWIE>(this.detach_SEDZIOWIEs));
			this._DRUZYNY = default(EntityRef<DRUZYNY>);
			this._DRUZYNY1 = default(EntityRef<DRUZYNY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_spot", Storage="_Id_spot", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_spot;
			}
			set
			{
				if ((this._Id_spot != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_spot = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_gospo", Storage="_Id_gospo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_Gospodarza
		{
			get
			{
				return this._Id_gospo;
			}
			set
			{
				if ((this._Id_gospo != value))
				{
					this.OnId_GospodarzaChanging(value);
					this.SendPropertyChanging();
					this._Id_gospo = value;
					this.SendPropertyChanged("Id_Gospodarza");
					this.OnId_GospodarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_gosc", Storage="_Id_gosc", DbType="Decimal(18,0) NOT NULL")]
		public decimal Id_Gościa
		{
			get
			{
				return this._Id_gosc;
			}
			set
			{
				if ((this._Id_gosc != value))
				{
					this.OnId_GościaChanging(value);
					this.SendPropertyChanging();
					this._Id_gosc = value;
					this.SendPropertyChanged("Id_Gościa");
					this.OnId_GościaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Data_spot", Storage="_Data_spot", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Spotkania
		{
			get
			{
				return this._Data_spot;
			}
			set
			{
				if ((this._Data_spot != value))
				{
					this.OnData_SpotkaniaChanging(value);
					this.SendPropertyChanging();
					this._Data_spot = value;
					this.SendPropertyChanged("Data_Spotkania");
					this.OnData_SpotkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Miejsce_spot", Storage="_Miejsce_spot", DbType="VarChar(15)")]
		public string Miejsce_Spotkania
		{
			get
			{
				return this._Miejsce_spot;
			}
			set
			{
				if ((this._Miejsce_spot != value))
				{
					this.OnMiejsce_SpotkaniaChanging(value);
					this.SendPropertyChanging();
					this._Miejsce_spot = value;
					this.SendPropertyChanged("Miejsce_Spotkania");
					this.OnMiejsce_SpotkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Wynik_gospo", Storage="_Wynik_gospo", DbType="Int")]
		public System.Nullable<int> Wynik_Gospodarza
		{
			get
			{
				return this._Wynik_gospo;
			}
			set
			{
				if ((this._Wynik_gospo != value))
				{
					this.OnWynik_GospodarzaChanging(value);
					this.SendPropertyChanging();
					this._Wynik_gospo = value;
					this.SendPropertyChanged("Wynik_Gospodarza");
					this.OnWynik_GospodarzaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Wynik_gosc", Storage="_Wynik_gosc", DbType="Int")]
		public System.Nullable<int> Wynik_Gościa
		{
			get
			{
				return this._Wynik_gosc;
			}
			set
			{
				if ((this._Wynik_gosc != value))
				{
					this.OnWynik_GościaChanging(value);
					this.SendPropertyChanging();
					this._Wynik_gosc = value;
					this.SendPropertyChanged("Wynik_Gościa");
					this.OnWynik_GościaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_BRAMKI", Storage="_BRAMKIs", ThisKey="Id", OtherKey="Id_Spotkania")]
		public EntitySet<BRAMKI> BRAMKIs
		{
			get
			{
				return this._BRAMKIs;
			}
			set
			{
				this._BRAMKIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_KARTKI", Storage="_KARTKIs", ThisKey="Id", OtherKey="Id_spot")]
		public EntitySet<KARTKI> KARTKIs
		{
			get
			{
				return this._KARTKIs;
			}
			set
			{
				this._KARTKIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_SEDZIOWIE", Storage="_SEDZIOWIEs", ThisKey="Id", OtherKey="Id_Spotkania")]
		public EntitySet<SEDZIOWIE> SEDZIOWIEs
		{
			get
			{
				return this._SEDZIOWIEs;
			}
			set
			{
				this._SEDZIOWIEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_SPOTKANIA", Storage="_DRUZYNY", ThisKey="Id_Gościa", OtherKey="Id", IsForeignKey=true)]
		public DRUZYNY DRUZYNY
		{
			get
			{
				return this._DRUZYNY.Entity;
			}
			set
			{
				DRUZYNY previousValue = this._DRUZYNY.Entity;
				if (((previousValue != value) 
							|| (this._DRUZYNY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DRUZYNY.Entity = null;
						previousValue.SPOTKANIAs.Remove(this);
					}
					this._DRUZYNY.Entity = value;
					if ((value != null))
					{
						value.SPOTKANIAs.Add(this);
						this._Id_gosc = value.Id;
					}
					else
					{
						this._Id_gosc = default(decimal);
					}
					this.SendPropertyChanged("DRUZYNY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_SPOTKANIA1", Storage="_DRUZYNY1", ThisKey="Id_Gospodarza", OtherKey="Id", IsForeignKey=true)]
		public DRUZYNY DRUZYNY1
		{
			get
			{
				return this._DRUZYNY1.Entity;
			}
			set
			{
				DRUZYNY previousValue = this._DRUZYNY1.Entity;
				if (((previousValue != value) 
							|| (this._DRUZYNY1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DRUZYNY1.Entity = null;
						previousValue.SPOTKANIAs1.Remove(this);
					}
					this._DRUZYNY1.Entity = value;
					if ((value != null))
					{
						value.SPOTKANIAs1.Add(this);
						this._Id_gospo = value.Id;
					}
					else
					{
						this._Id_gospo = default(decimal);
					}
					this.SendPropertyChanged("DRUZYNY1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BRAMKIs(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = this;
		}
		
		private void detach_BRAMKIs(BRAMKI entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = null;
		}
		
		private void attach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = this;
		}
		
		private void detach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = null;
		}
		
		private void attach_SEDZIOWIEs(SEDZIOWIE entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = this;
		}
		
		private void detach_SEDZIOWIEs(SEDZIOWIE entity)
		{
			this.SendPropertyChanging();
			entity.SPOTKANIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRENERZY")]
	public partial class TRENERZY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_tren;
		
		private System.Nullable<decimal> _Id_druz;
		
		private string _Imie_tren;
		
		private string _Nazwisko_tren;
		
		private System.Nullable<System.DateTime> _Data_ur_tren;
		
		private EntityRef<DRUZYNY> _DRUZYNY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnDruzynaChanging(System.Nullable<decimal> value);
    partial void OnDruzynaChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnDataUrodzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataUrodzeniaChanged();
    #endregion
		
		public TRENERZY()
		{
			this._DRUZYNY = default(EntityRef<DRUZYNY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_tren", Storage="_Id_tren", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_tren;
			}
			set
			{
				if ((this._Id_tren != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_tren = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_druz", Storage="_Id_druz", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Druzyna
		{
			get
			{
				return this._Id_druz;
			}
			set
			{
				if ((this._Id_druz != value))
				{
					this.OnDruzynaChanging(value);
					this.SendPropertyChanging();
					this._Id_druz = value;
					this.SendPropertyChanged("Druzyna");
					this.OnDruzynaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Imie_tren", Storage="_Imie_tren", DbType="VarChar(15)")]
		public string Imie
		{
			get
			{
				return this._Imie_tren;
			}
			set
			{
				if ((this._Imie_tren != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie_tren = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Nazwisko_tren", Storage="_Nazwisko_tren", DbType="VarChar(15)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko_tren;
			}
			set
			{
				if ((this._Nazwisko_tren != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko_tren = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Data_ur_tren", Storage="_Data_ur_tren", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataUrodzenia
		{
			get
			{
				return this._Data_ur_tren;
			}
			set
			{
				if ((this._Data_ur_tren != value))
				{
					this.OnDataUrodzeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_ur_tren = value;
					this.SendPropertyChanged("DataUrodzenia");
					this.OnDataUrodzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DRUZYNY_TRENERZY", Storage="_DRUZYNY", ThisKey="Druzyna", OtherKey="Id", IsForeignKey=true)]
		public DRUZYNY DRUZYNY
		{
			get
			{
				return this._DRUZYNY.Entity;
			}
			set
			{
				DRUZYNY previousValue = this._DRUZYNY.Entity;
				if (((previousValue != value) 
							|| (this._DRUZYNY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DRUZYNY.Entity = null;
						previousValue.TRENERZies.Remove(this);
					}
					this._DRUZYNY.Entity = value;
					if ((value != null))
					{
						value.TRENERZies.Add(this);
						this._Id_druz = value.Id;
					}
					else
					{
						this._Id_druz = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("DRUZYNY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SEDZIOWIE")]
	public partial class SEDZIOWIE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id_sed;
		
		private System.Nullable<decimal> _Id_spot;
		
		private string _Imie_sed;
		
		private string _Nazwisko_sed;
		
		private System.Nullable<System.DateTime> _Data_ur_sed;
		
		private System.Nullable<int> _Ilosc_wydanych_kartek_sed;
		
		private EntitySet<KARTKI> _KARTKIs;
		
		private EntityRef<SPOTKANIA> _SPOTKANIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnId_SpotkaniaChanging(System.Nullable<decimal> value);
    partial void OnId_SpotkaniaChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnData_UrodzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnData_UrodzeniaChanged();
    partial void OnIlość_KartekChanging(System.Nullable<int> value);
    partial void OnIlość_KartekChanged();
    #endregion
		
		public SEDZIOWIE()
		{
			this._KARTKIs = new EntitySet<KARTKI>(new Action<KARTKI>(this.attach_KARTKIs), new Action<KARTKI>(this.detach_KARTKIs));
			this._SPOTKANIA = default(EntityRef<SPOTKANIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_sed", Storage="_Id_sed", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id_sed;
			}
			set
			{
				if ((this._Id_sed != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id_sed = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Id_spot", Storage="_Id_spot", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Id_Spotkania
		{
			get
			{
				return this._Id_spot;
			}
			set
			{
				if ((this._Id_spot != value))
				{
					this.OnId_SpotkaniaChanging(value);
					this.SendPropertyChanging();
					this._Id_spot = value;
					this.SendPropertyChanged("Id_Spotkania");
					this.OnId_SpotkaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Imie_sed", Storage="_Imie_sed", DbType="VarChar(15)")]
		public string Imie
		{
			get
			{
				return this._Imie_sed;
			}
			set
			{
				if ((this._Imie_sed != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie_sed = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Nazwisko_sed", Storage="_Nazwisko_sed", DbType="VarChar(15)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko_sed;
			}
			set
			{
				if ((this._Nazwisko_sed != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko_sed = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Data_ur_sed", Storage="_Data_ur_sed", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Urodzenia
		{
			get
			{
				return this._Data_ur_sed;
			}
			set
			{
				if ((this._Data_ur_sed != value))
				{
					this.OnData_UrodzeniaChanging(value);
					this.SendPropertyChanging();
					this._Data_ur_sed = value;
					this.SendPropertyChanged("Data_Urodzenia");
					this.OnData_UrodzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Ilosc_wydanych_kartek_sed", Storage="_Ilosc_wydanych_kartek_sed", DbType="Int")]
		public System.Nullable<int> Ilość_Kartek
		{
			get
			{
				return this._Ilosc_wydanych_kartek_sed;
			}
			set
			{
				if ((this._Ilosc_wydanych_kartek_sed != value))
				{
					this.OnIlość_KartekChanging(value);
					this.SendPropertyChanging();
					this._Ilosc_wydanych_kartek_sed = value;
					this.SendPropertyChanged("Ilość_Kartek");
					this.OnIlość_KartekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SEDZIOWIE_KARTKI", Storage="_KARTKIs", ThisKey="Id", OtherKey="Id_sed")]
		public EntitySet<KARTKI> KARTKIs
		{
			get
			{
				return this._KARTKIs;
			}
			set
			{
				this._KARTKIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SPOTKANIA_SEDZIOWIE", Storage="_SPOTKANIA", ThisKey="Id_Spotkania", OtherKey="Id", IsForeignKey=true)]
		public SPOTKANIA SPOTKANIA
		{
			get
			{
				return this._SPOTKANIA.Entity;
			}
			set
			{
				SPOTKANIA previousValue = this._SPOTKANIA.Entity;
				if (((previousValue != value) 
							|| (this._SPOTKANIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SPOTKANIA.Entity = null;
						previousValue.SEDZIOWIEs.Remove(this);
					}
					this._SPOTKANIA.Entity = value;
					if ((value != null))
					{
						value.SEDZIOWIEs.Add(this);
						this._Id_spot = value.Id;
					}
					else
					{
						this._Id_spot = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("SPOTKANIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.SEDZIOWIE = this;
		}
		
		private void detach_KARTKIs(KARTKI entity)
		{
			this.SendPropertyChanging();
			entity.SEDZIOWIE = null;
		}
	}
}
#pragma warning restore 1591
