<?xml version="1.0" encoding="utf-8"?><Database Name="C:\USERS\DARIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\SSDT\LOGIN.MDF" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=C:\USERS\DARIU\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\SSDT\LOGIN.MDF;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="Projekt_Ekstraklasa.Properties.Settings" SettingsPropertyName="C__USERS_DARIU_APPDATA_LOCAL_MICROSOFT_VISUALSTUDIO_SSDT_LOGIN_MDFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="UserPassword" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NameAddress" Member="EmailAddress" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>